### ISSUE TITLE
RPC return panic error sometimes on broadcastTxCommit request from LCD

### ISSUE THREAD

**Issue by bluedisk** [terra-project/core#125]
returned error message from LCD is following:

```
E[2019-04-23|17:10:35.750] Panic in RPC HTTP handler                    module=rest-server err="runtime error: invalid memory address or nil pointer dereference" stack="
 runtime error: invalid memory address or nil pointer dereference" stack="goroutine 5559 [running]:
 runtime/debug.Stack(0xc0020aead0, 0x4a30980, 0x57dab20)
 	/usr/local/go/src/runtime/debug/stack.go:24 +0x9d
 github.com/tendermint/tendermint/rpc/lib/server.RecoverAndLogHandler.func1.1(0xc0032d54a0, 0x505bbe0, 0xc000c08fb0, 0xbf27cf6d52818898, 0x7383d94f45f, 0x57f3f60, 0xc002bd0000)
 	go/pkg/mod/github.com/tendermint/tendermint@v0.31.4/rpc/lib/server/http_server.go:140 +0x552
 panic(0x4a30980, 0x57dab20)
 	/usr/local/go/src/runtime/panic.go:522 +0x1b5
 github.com/cosmos/cosmos-sdk/types.NewResponseFormatBroadcastTxCommit(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
 	go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.34.0/types/result.go:110 +0x58
 github.com/cosmos/cosmos-sdk/client/context.CLIContext.BroadcastTxCommit(0xc0001e4ee0, 0xc000c08f70, 0x5074f40, 0xc000c0d520, 0x0, 0x0, 0x50416c0, 0xc0000ce000, 0x4b4a524, 0x4, ...)
 	go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.34.0/client/context/broadcast.go:46 +0x3f1
 github.com/cosmos/cosmos-sdk/client/context.CLIContext.BroadcastTx(0xc0001e4ee0, 0xc000c08f70, 0x5074f40, 0xc000c0d520, 0x0, 0x0, 0x50416c0, 0xc0000ce000, 0x4b4a524, 0x4, ...)
 	go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.34.0/client/context/broadcast.go:23 +0x212
 github.com/cosmos/cosmos-sdk/client/tx.BroadcastTxRequest.func1(0x5056ae0, 0xc0032d54a0, 0xc002bd0200)
 	go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.34.0/client/tx/broadcast.go:54 +0x2b6
 net/http.HandlerFunc.ServeHTTP(0xc000c0d040, 0x5056ae0, 0xc0032d54a0, 0xc002bd0200)
 	/usr/local/go/src/net/http/server.go:1995 +0x44
 github.com/gorilla/mux.(*Router).ServeHTTP(0xc0001c8e40, 0x5056ae0, 0xc0032d54a0, 0xc002bd0000)
 	go/pkg/mod/github.com/gorilla/mux@v1.7.0/mux.go:212 +0xe3
 github.com/tendermint/tendermint/rpc/lib/server.maxBytesHandler.ServeHTTP(0x5040500, 0xc0001c8e40, 0xf4240, 0x5056ae0, 0xc0032d54a0, 0xc002bd0000)
 	go/pkg/mod/github.com/tendermint/tendermint@v0.31.4/rpc/lib/server/http_server.go:185 +0xd0
 github.com/tendermint/tendermint/rpc/lib/server.RecoverAndLogHandler.func1(0x5057160, 0xc002857ea0, 0xc002bd0000)
 	go/pkg/mod/github.com/tendermint/tendermint@v0.31.4/rpc/lib/server/http_server.go:158 +0x317
 net/http.HandlerFunc.ServeHTTP(0xc00099e060, 0x5057160, 0xc002857ea0, 0xc002bd0000)
 	/usr/local/go/src/net/http/server.go:1995 +0x44
 net/http.serverHandler.ServeHTTP(0xc0000ec410, 0x5057160, 0xc002857ea0, 0xc002bd0000)
 	/usr/local/go/src/net/http/server.go:2774 +0xa8
 net/http.(*conn).serve(0xc002bce000, 0x505b060, 0xc002bac180)
 	/usr/local/go/src/net/http/server.go:1878 +0x851
 created by net/http.(*Server).Serve
 	/usr/local/go/src/net/http/server.go:2884 +0x2f4
"
 ```

**Comment by bluedisk** [comment]
one of error that was logged in PRC node at the error was rasing.
```
E[2019-04-23|17:10:31.112] Connection failed @ recvRoutine (reading byte) module=p2p peer=1e1677e4ed9acf4e28de40b67ac01554aed1a29e@52.78.69.160:26656 conn=MConn{52.78.69.160:26656} 
err="read tcp 172.16.28.37:49340->52.78.69.160:26656: read: connection reset by peer"

E[2019-04-23|17:10:31.112] Stopping peer for error                      module=p2p peer="Peer{MConn{52.78.69.160:26656} 1e1677e4ed9acf4e28de40b67ac01554aed1a29e out}" 
err="read tcp 172.16.28.37:49340->52.78.69.160:26656: read: connection reset by peer"

E[2019-04-23|17:10:31.117] Connection failed @ recvRoutine (reading byte) module=p2p peer=6d20ac95f60662dbfc21dd039aa8c1cfa83f221d@106.10.45.205:26656 conn=MConn{106.10.45.205:26656} 
err="read tcp 172.16.28.37:49341->106.10.45.205:26656: read: connection reset by peer"

E[2019-04-23|17:10:31.117] Stopping peer for error                      module=p2p peer="Peer{MConn{106.10.45.205:26656} 6d20ac95f60662dbfc21dd039aa8c1cfa83f221d out}" 
err="read tcp 172.16.28.37:49341->106.10.45.205:26656: read: connection reset by peer"

E[2019-04-23|17:10:35.748] Error on broadcastTxCommit                   module=rpc err="Timed out waiting for tx to be included in a block"
```
