### ISSUE TITLE
Query oracle price with CLI and REST don't work

### ISSUE THREAD

**Issue by kwunyeung** [terra-project/core#139]
I tried to query the price on `soju-0008` but it failed.

`terracli q oracle price --denom usdr --node https://rpc.soju.bigdipper.live:443 --chain-id soju-0008`

```sh
panic: Error initializing DB: resource temporarily unavailable

goroutine 1 [running]:
github.com/tendermint/tendermint/libs/db.NewDB(0x4b50621, 0xa, 0x4b4d927, 0x7, 0xc000c08ea0, 0x24, 0x24, 0x0)
	/Users/kwunyueng/go/pkg/mod/github.com/tendermint/tendermint@v0.31.4/libs/db/db.go:51 +0x274
github.com/tendermint/tendermint/lite/proxy.NewVerifier(0x7ffeefbff9f3, 0x9, 0xc000c08ea0, 0x24, 0x5064380, 0xc000c7a0e0, 0x505c280, 0x5815388, 0xa, 0xc0003ff3c0, ...)
	/Users/kwunyueng/go/pkg/mod/github.com/tendermint/tendermint@v0.31.4/lite/proxy/verifier.go:17 +0x320
github.com/cosmos/cosmos-sdk/client/context.createVerifier(0x0, 0x0)
	/Users/kwunyueng/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.34.0/client/context/context.go:137 +0x3d1
github.com/cosmos/cosmos-sdk/client/context.NewCLIContext(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/Users/kwunyueng/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.34.0/client/context/context.go:79 +0x5f8
github.com/terra-project/core/x/oracle/client/cli.GetCmdQueryPrice.func1(0xc000c2cc80, 0xc00016ea80, 0x0, 0x6, 0x0, 0x0)
	/Users/kwunyueng/go/src/github.com/terra-project/core/x/oracle/client/cli/query.go:35 +0x5b
github.com/spf13/cobra.(*Command).execute(0xc000c2cc80, 0xc00016e960, 0x6, 0x6, 0xc000c2cc80, 0xc00016e960)
	/Users/kwunyueng/go/pkg/mod/github.com/spf13/cobra@v0.0.3/command.go:762 +0x465
github.com/spf13/cobra.(*Command).ExecuteC(0xc0001f2780, 0x4474abf, 0xc0001f2780, 0x4b49c4f)
	/Users/kwunyueng/go/pkg/mod/github.com/spf13/cobra@v0.0.3/command.go:852 +0x2ec
github.com/spf13/cobra.(*Command).Execute(...)
	/Users/kwunyueng/go/pkg/mod/github.com/spf13/cobra@v0.0.3/command.go:800
github.com/tendermint/tendermint/libs/cli.Executor.Execute(0xc0001f2780, 0x4f14888, 0x2, 0xc000b15cc0)
	/Users/kwunyueng/go/pkg/mod/github.com/tendermint/tendermint@v0.31.4/libs/cli/setup.go:89 +0x3c
main.main()
	/Users/kwunyueng/go/src/github.com/terra-project/core/cmd/terracli/main.go:124 +0x8ca
```

**Comment by kwunyeung** [comment]
Seems only not work for remote query. And that's why REST also won't work.

**Comment by kwunyeung** [comment]
I know what was happening. As I was running LCD and terracli was trying to access the db and resources were locked. Not an issue for the moment.
