### ISSUE TITLE
[BUG] Querying /bank/balance RPC throws error

### ISSUE THREAD

**Issue by winslyn** [terra-project/core#221]
**Describe the bug**

when querying `/bank/balances/terra1lsjc8870ky0f0s6qh2h6emk67fv4kfsn2whnh`, the rest-server throws an error. After just restarting the rest-server, the error disappeared.

Request:
```
curl http://127.0.0.1:1317/bank/balances/terra1lsjc8870ky0f0s6qh2h6emk67fv4kfsn2whnh
```

Response from the rest-server:
```
Panic in RPC HTTP handler                    module=rest-server err="unmarshal to auth.Account failed after 4 bytes (unreco
gnized prefix bytes 539D5760): 539D57600A9C010A6C0A14FC25839FCFB11E97C340BAAFACEEDAF2595B245012120A04756B7277120A3233303039373031343612140A05756C756E6
1120B35373037333639303134371A26EB5AE9872103DFF0A014A22C40EDF32A5948E42F70259BA9C6176181870E5FF9CEDDD471B6F7204C280B12150A05756C756E61120C3537333931333
0303030303022150A05756C756E61120C343030303030303030303030128F010A05756C756E61122008E0909EE70510E0AABCE8051A1231303030303030303030303030303030303012200
8E0CDC1E80510E0E7DFE9051A12313030303030303030303030303030303030122008E0E7DFE90510E081FEEA051A12313030303030303030303030303030303030122008E0CCCDF20510E
0E6EBF3051A12373030303030303030303030303030303030" stack="goroutine 10285173 [running]:\nruntime/debug.Stack(0xc0003375f8, 0xe21500, 0xc000d86950)\n\t
/usr/local/go/src/runtime/debug/stack.go:24 +0x9d\ngithub.com/tendermint/tendermint/rpc/lib/server.RecoverAndLogHandler.func1.1(0xc0021e8b20, 0x146116
0, 0xc000c065a0, 0xbf4ac640cd38ebd5, 0x1315208e60fea1, 0x1dfa080, 0xc0017c9100)\n\t/home/ubuntu/go/pkg/mod/github.com/tendermint/tendermint@v0.31.5/rp
c/lib/server/http_server.go:140 +0x552\npanic(0xe21500, 0xc000d86950)\n\t/usr/local/go/src/runtime/panic.go:522 +0x1b5\ngithub.com/cosmos/cosmos-sdk/c
lient/context.GetAccountDecoder.func1(0xc002034780, 0x135, 0x135, 0xc000bb3ac0, 0x0, 0x0, 0x1446bc0)\n\t/home/ubuntu/go/pkg/mod/github.com/!yun!suk-!y
eo/cosmos-sdk@v0.34.7-terra/client/context/context.go:164 +0xd7\ngithub.com/cosmos/cosmos-sdk/x/auth/client/rest.QueryBalancesRequestHandlerFn.func1(0
x145c0e0, 0xc0021e8b20, 0xc0017c9300)\n\t/home/ubuntu/go/pkg/mod/github.com/!yun!suk-!yeo/cosmos-sdk@v0.34.7-terra/x/auth/client/rest/query.go:96 +0x3
38\nnet/http.HandlerFunc.ServeHTTP(0xc000bf2ba0, 0x145c0e0, 0xc0021e8b20, 0xc0017c9300)\n\t/usr/local/go/src/net/http/server.go:1995 +0x44\ngithub.com
/gorilla/mux.(*Router).ServeHTTP(0xc000b6cc00, 0x145c0e0, 0xc0021e8b20, 0xc0017c9100)\n\t/home/ubuntu/go/pkg/mod/github.com/gorilla/mux@v1.7.0/mux.go:
212 +0xe3\ngithub.com/tendermint/tendermint/rpc/lib/server.maxBytesHandler.ServeHTTP(0x1445b00, 0xc000b6cc00, 0xf4240, 0x145c0e0, 0xc0021e8b20, 0xc001
7c9100)\n\t/home/ubuntu/go/pkg/mod/github.com/tendermint/tendermint@v0.31.5/rpc/lib/server/http_server.go:185 +0xd0\ngithub.com/tendermint/tendermint/
rpc/lib/server.RecoverAndLogHandler.func1(0x145c760, 0xc0027ac1c0, 0xc0017c9100)\n\t/home/ubuntu/go/pkg/mod/github.com/tendermint/tendermint@v0.31.5/r
pc/lib/server/http_server.go:158 +0x317\nnet/http.HandlerFunc.ServeHTTP(0xc000923fb0, 0x145c760, 0xc0027ac1c0, 0xc0017c9100)\n\t/usr/local/go/src/net/
http/server.go:1995 +0x44\nnet/http.serverHandler.ServeHTTP(0xc00030a0d0, 0x145c760, 0xc0027ac1c0, 0xc0017c9100)\n\t/usr/local/go/src/net/http/server.
go:2774 +0xa8\nnet/http.(*conn).serve(0xc0029d9220, 0x14605e0, 0xc000de8b80)\n\t/usr/local/go/src/net/http/server.go:1878 +0x851\ncreated by net/http.
(*Server).Serve\n\t/usr/local/go/src/net/http/server.go:2884 +0x2f4\n"
```

Reponse from the curl:
```
{
  "jsonrpc": "2.0",
  "id": "",
  "error": {
    "code": -32603,
    "message": "Internal error",
    "data": "unmarshal to auth.Account failed after 4 bytes (unrecognized prefix bytes 539D5760): 539D57600A9C010A6C0A14FC25839FCFB11E97C340BAAFACEEDAF2595B245012120A04756B7277120A3233303039373031343612140A05756C756E61120B35373037333639303134371A26EB5AE9872103DFF0A014A22C40EDF32A5948E42F70259BA9C6176181870E5FF9CEDDD471B6F7204C280B12150A05756C756E61120C35373339313330303030303022150A05756C756E61120C343030303030303030303030128F010A05756C756E61122008E0909EE70510E0AABCE8051A12313030303030303030303030303030303030122008E0CDC1E80510E0E7DFE9051A12313030303030303030303030303030303030122008E0E7DFE90510E081FEEA051A12313030303030303030303030303030303030122008E0CCCDF20510E0E6EBF3051A12373030303030303030303030303030303030"
  }
}
```

**To Reproduce**
unable to reproduce after restarting the rest-server

**Context & versions**
```
$ terrad version --long
core: 0.2.3
git commit: 3162406eeecfb7ecc299a4da0311d667f3ad5f1d
go.sum hash: 16b4380417ccc95621c3447fd84be018324ff61de198333dab7ba18bac931244
build tags: netgo ledger
go version go1.12.4 linux/amd64
```

**Comment by YunSuk-Yeo** [comment]
terra1lsjc8870ky0f0s6qh2h6emk67fv4kfsn2whnh is invalid terra address. you can check validation with $ terracli query account terra1lsjc8870ky0f0s6qh2h6emk67fv4kfsn2whnh --trust-node

**Comment by winslyn** [comment]
You are right. I must've copied it wrong.

Thanks!
