### ISSUE TITLE
[BUG] LCD crash after upgrading to v0.2.6 without --trust-node

### ISSUE THREAD

**Issue by kwunyeung** [terra-project/core#263]
**Describe the bug**
After upgrading to `v0.2.6`, LCD cannot start with `--chain-id columbus-2` flag. Instead if I put `--trust-node`, it will start and run correctly.

Here is the panic stack trace.

```
Oct 31 13:23:13 explorer-node terracli[16759]: panic: Error initializing DB: leveldb: manifest corrupted (field 'comparer'): missing [file=MANIFEST-000018]
Oct 31 13:23:13 explorer-node terracli[16759]: goroutine 1 [running]:
Oct 31 13:23:13 explorer-node terracli[16759]: github.com/tendermint/tendermint/libs/db.NewDB(0xf8dcde, 0xa, 0xf8cb9d, 0x9, 0xc000931500, 0x15, 0xc0009314e0, 0x16)
Oct 31 13:23:13 explorer-node terracli[16759]:         /home/kwunyueng/go/pkg/mod/github.com/tendermint/tendermint@v0.31.11/libs/db/db.go:71 +0x274
Oct 31 13:23:13 explorer-node terracli[16759]: github.com/tendermint/tendermint/lite/proxy.NewVerifier(0x7fff4e0a0f00, 0xa, 0xc000931500, 0x15, 0x149f800, 0xc000879d40, 0x1497fe0, 0x1dc1d28, 0xa, 0x86957c, ...)
Oct 31 13:23:13 explorer-node terracli[16759]:         /home/kwunyueng/go/pkg/mod/github.com/tendermint/tendermint@v0.31.11/lite/proxy/verifier.go:17 +0x2dd
Oct 31 13:23:13 explorer-node terracli[16759]: github.com/cosmos/cosmos-sdk/client/context.createVerifier(0x0, 0x0)
Oct 31 13:23:13 explorer-node terracli[16759]:         /home/kwunyueng/go/pkg/mod/github.com/!yun!suk-!yeo/cosmos-sdk@v0.35.5-terra/client/context/context.go:139 +0x39e
Oct 31 13:23:13 explorer-node terracli[16759]: github.com/cosmos/cosmos-sdk/client/context.NewCLIContext(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
Oct 31 13:23:13 explorer-node terracli[16759]:         /home/kwunyueng/go/pkg/mod/github.com/!yun!suk-!yeo/cosmos-sdk@v0.35.5-terra/client/context/context.go:81 +0x5ed
Oct 31 13:23:13 explorer-node terracli[16759]: github.com/cosmos/cosmos-sdk/client/lcd.NewRestServer(0xc00011ee00, 0xc000894280)
Oct 31 13:23:13 explorer-node terracli[16759]:         /home/kwunyueng/go/pkg/mod/github.com/!yun!suk-!yeo/cosmos-sdk@v0.35.5-terra/client/lcd/root.go:42 +0x7f
Oct 31 13:23:13 explorer-node terracli[16759]: github.com/cosmos/cosmos-sdk/client/lcd.ServeCommand.func1(0xc000894280, 0xc000878db0, 0x0, 0x3, 0x0, 0x0)
Oct 31 13:23:13 explorer-node terracli[16759]:         /home/kwunyueng/go/pkg/mod/github.com/!yun!suk-!yeo/cosmos-sdk@v0.35.5-terra/client/lcd/root.go:86 +0x37
Oct 31 13:23:13 explorer-node terracli[16759]: github.com/spf13/cobra.(*Command).execute(0xc000894280, 0xc000878cf0, 0x3, 0x3, 0xc000894280, 0xc000878cf0)
Oct 31 13:23:13 explorer-node terracli[16759]:         /home/kwunyueng/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:826 +0x460
Oct 31 13:23:13 explorer-node terracli[16759]: github.com/spf13/cobra.(*Command).ExecuteC(0xc000126c80, 0x894a40, 0xc000126c80, 0xf87043)
Oct 31 13:23:13 explorer-node terracli[16759]:         /home/kwunyueng/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:914 +0x2fb
Oct 31 13:23:13 explorer-node terracli[16759]: github.com/spf13/cobra.(*Command).Execute(...)
Oct 31 13:23:13 explorer-node terracli[16759]:         /home/kwunyueng/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:864
Oct 31 13:23:13 explorer-node terracli[16759]: github.com/tendermint/tendermint/libs/cli.Executor.Execute(0xc000126c80, 0x1357438, 0x2, 0xc000a81580)
Oct 31 13:23:13 explorer-node terracli[16759]:         /home/kwunyueng/go/pkg/mod/github.com/tendermint/tendermint@v0.31.11/libs/cli/setup.go:89 +0x3c
Oct 31 13:23:13 explorer-node terracli[16759]: main.main()
Oct 31 13:23:13 explorer-node terracli[16759]:         /home/kwunyueng/go/src/github.com/terra-project/core/cmd/terracli/main.go:130 +0x905
```

**To Reproduce**
run `terracli rest-server --chain-id columbus-2`

**Context & versions**
`v0.2.6`

**Comment by kwunyeung** [comment]
Hm... this issue can be reproduced on one node but there is no such problem on another node.

**Comment by YunSuk-Yeo** [comment]
@kwunyeung Thanks for reporting the issue.

I investigated this problem. but don't know exact reasons. It is level DB dirty bit problem, can be occurred due to so many reasons like ungraceful shutdown or just deletion of  a part of manifest files. 

Anyway to solve the problem itself, do delete ~/.terracli/.gaialight folder to reset verifier level db.

**Comment by kwunyeung** [comment]
This works. Thanks! I do have experience on different chains that level db may just be unintentionally be corrupted.
