### ISSUE TITLE
[BUG] terracli keys add panics

### ISSUE THREAD

**Issue by StakerSpace** [terra-project/core#389]
**Describe the bug**
on `v0.4.0-rc3` (downloaded binaries) I get the following when adding keys 

```
panic: No such interface “org.freedesktop.DBus.Properties” on object at path /

goroutine 1 [running]:
github.com/cosmos/cosmos-sdk/crypto/keys.keyringKeybase.writeInfo(0x1ae4888, 0x1ae4880, 0xc001302ed0, 0x1, 0x1, 0xc001302ee0, 0x1, 0x1, 0x1cd1b20, 0xc001312d20, ...)
	/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.39.1/crypto/keys/keyring.go:478 +0x38c
github.com/cosmos/cosmos-sdk/crypto/keys.keyringKeybase.writeLocalKey(0x1ae4888, 0x1ae4880, 0xc001302ed0, 0x1, 0x1, 0xc001302ee0, 0x1, 0x1, 0x1cd1b20, 0xc001312d20, ...)
	/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.39.1/crypto/keys/keyring.go:464 +0x189
github.com/cosmos/cosmos-sdk/crypto/keys.baseKeybase.CreateAccount(0x1ae4888, 0x1ae4880, 0xc001302ed0, 0x1, 0x1, 0xc001302ee0, 0x1, 0x1, 0x1cbf820, 0xc000012280, ...)
	/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.39.1/crypto/keys/keybase_base.go:171 +0x192
github.com/cosmos/cosmos-sdk/crypto/keys.keyringKeybase.CreateAccount(...)
	/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.39.1/crypto/keys/keyring.go:106
github.com/cosmos/cosmos-sdk/client/keys.RunAddCmd(0xc00130fb80, 0xc001312810, 0x1, 0x3, 0x1ce9600, 0xc00012da40, 0xc0012d9140, 0xc000e19c38, 0x5e4fe7)
	/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.39.1/client/keys/add.go:273 +0x732
github.com/cosmos/cosmos-sdk/client/keys.runAddCmd(0xc00130fb80, 0xc001312810, 0x1, 0x3, 0x0, 0x0)
	/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.39.1/client/keys/add.go:99 +0x166
github.com/spf13/cobra.(*Command).execute(0xc00130fb80, 0xc0013127e0, 0x3, 0x3, 0xc00130fb80, 0xc0013127e0)
	/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:842 +0x453
github.com/spf13/cobra.(*Command).ExecuteC(0xc0000d1b80, 0x88c480, 0xc0000d1b80, 0x16ffb1f)
	/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:950 +0x349
github.com/spf13/cobra.(*Command).Execute(...)
	/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:887
github.com/tendermint/tendermint/libs/cli.Executor.Execute(0xc0000d1b80, 0x1ae7d28, 0x2, 0xc0004e10a0)
	/go/pkg/mod/github.com/tendermint/tendermint@v0.33.7/libs/cli/setup.go:89 +0x3c
main.main()
	/go/src/github.com/terra-project/core/cmd/terracli/main.go:81 +0x383
```

**To Reproduce**
`terrad init --chain-id=tequila-0004 "Staker Space"`
`terracli keys add space`

**Comment by hanjukim** [comment]
are you using Linux binaries?

**Comment by StakerSpace** [comment]
Using Ubuntu:
```
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.1 LTS
Release:	20.04
Codename:	focal
```

Used these binaries: terra_0.4.0_rc.3_Linux_x86_64.tar.gz

**Comment by StakerSpace** [comment]
Same with `0.4.0-rc4` 
Tried to see if rc4 recognized the keys I made with `v0.3.7` it doesn't recognize it:

```
$terracli keys list
[]
```
When recovering and migrating it gives the same type of error as in the initial issue post:

- terracli keys add spaceTest --recover
- terracli keys migrate

```
> Enter your bip39 mnemonic
[Inserting bip39 mnemonic}

panic: No such interface “org.freedesktop.DBus.Properties” on object at path /

goroutine 1 [running]:
github.com/cosmos/cosmos-sdk/crypto/keys.keyringKeybase.writeInfo(0x1ae3890, 0x1ae3888, 0xc0001f85f0, 0x1, 0x1, 0xc0001f8600, 0x1, 0x1, 0x1cd0b20, 0xc001151980, ...)
	/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.39.1/crypto/keys/keyring.go:478 +0x38c
github.com/cosmos/cosmos-sdk/crypto/keys.keyringKeybase.writeLocalKey(0x1ae3890, 0x1ae3888, 0xc0001f85f0, 0x1, 0x1, 0xc0001f8600, 0x1, 0x1, 0x1cd0b20, 0xc001151980, ...)
	/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.39.1/crypto/keys/keyring.go:464 +0x189
github.com/cosmos/cosmos-sdk/crypto/keys.baseKeybase.CreateAccount(0x1ae3890, 0x1ae3888, 0xc0001f85f0, 0x1, 0x1, 0xc0001f8600, 0x1, 0x1, 0x1cbe820, 0xc000136d20, ...)
	/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.39.1/crypto/keys/keybase_base.go:171 +0x192
github.com/cosmos/cosmos-sdk/crypto/keys.keyringKeybase.CreateAccount(...)
	/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.39.1/crypto/keys/keyring.go:106
github.com/cosmos/cosmos-sdk/client/keys.RunAddCmd(0xc00117a840, 0xc00105ffc0, 0x1, 0x2, 0x1ce8600, 0xc000136cd0, 0xc00116e720, 0xc0001c3c38, 0x5e4fe7)
	/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.39.1/client/keys/add.go:273 +0x732
github.com/cosmos/cosmos-sdk/client/keys.runAddCmd(0xc00117a840, 0xc00105ffc0, 0x1, 0x2, 0x0, 0x0)
	/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.39.1/client/keys/add.go:99 +0x166
github.com/spf13/cobra.(*Command).execute(0xc00117a840, 0xc00105ffa0, 0x2, 0x2, 0xc00117a840, 0xc00105ffa0)
	/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:842 +0x453
github.com/spf13/cobra.(*Command).ExecuteC(0xc000646840, 0x88c480, 0xc000646840, 0x16feb1f)
	/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:950 +0x349
github.com/spf13/cobra.(*Command).Execute(...)
	/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:887
github.com/tendermint/tendermint/libs/cli.Executor.Execute(0xc000646840, 0x1ae6d30, 0x2, 0xc0010252c0)
	/go/pkg/mod/github.com/tendermint/tendermint@v0.33.7/libs/cli/setup.go:89 +0x3c
main.main()
	/go/src/github.com/terra-project/core/cmd/terracli/main.go:81 +0x383
```

You think this can be fixed before launch of the network or gentx submission? Should I switch machines?

**Comment by YunSuk-Yeo** [comment]
reported from StakerSpace team, it resolved after changing the machine.
