### ISSUE TITLE
[BUG] Unable to start terracli rest-server after upgrade to 0.4.0

### ISSUE THREAD

**Issue by amanusk** [terra-project/core#393]
**Describe the bug**
After the upgrade to `0.4.0-rc4` getting the following trace:
```
panic: statik/fs: no zip data registered

goroutine 1 [running]:
github.com/terra-project/core/client/lcd.(*RestServer).registerSwaggerUI(0xc000169e00)
        /home/amanusk/go/src/github.com/terra-project/core/client/lcd/root.go:112 +0x14b
github.com/terra-project/core/client/lcd.ServeCommand.func1(0xc0010cc000, 0xc000fb7770, 0x0, 0x5, 0x0, 0x0)
        /home/amanusk/go/src/github.com/terra-project/core/client/lcd/root.go:91 +0x5d
github.com/spf13/cobra.(*Command).execute(0xc0010cc000, 0xc000fb7720, 0x5, 0x5, 0xc0010cc000, 0xc000fb7720)
        /home/amanusk/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:842 +0x453
github.com/spf13/cobra.(*Command).ExecuteC(0xc0000e8840, 0x890ec0, 0xc0000e8840, 0x12c12df)
        /home/amanusk/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:950 +0x349
github.com/spf13/cobra.(*Command).Execute(...)
        /home/amanusk/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:887
github.com/tendermint/tendermint/libs/cli.Executor.Execute(0xc0000e8840, 0x1456fd0, 0x2, 0xc000fc7460)
        /home/amanusk/go/pkg/mod/github.com/tendermint/tendermint@v0.33.7/libs/cli/setup.go:89 +0x3c
main.main()
        /home/amanusk/go/src/github.com/terra-project/core/cmd/terracli/main.go:81 +0x383
```

**To Reproduce**
* clone repo
* make install
* Run `terrad`
* Run `terracli rest-server`

**Context & versions**
terrad: `0.4.0-rc.4`
terracli: `0.4.0-rc.4`

**(if applicable) suggested solution**
Downgrading to 0.3.6 works as usual

**Comment by YunSuk-Yeo** [comment]
It is due to absence of swagger binary.  You can solve it by running:
```
$ make update-swagger-docs
```

**Comment by YunSuk-Yeo** [comment]
I will upload swagger binary at next release

**Comment by amanusk** [comment]
Thanks, that fixed it. Feel free to close now or after the next release.

**Comment by YunSuk-Yeo** [comment]
Yea PR will close it :)
