### ISSUE TITLE
[BUG] How this is different from classic-terra/core

### ISSUE THREAD

**Issue by pronvis** [terra-project/core#820]
Hello!
What is the difference between this repo & https://github.com/classic-terra/core/ ?
I could start https://github.com/classic-terra/core/ and it works as expected. But if then I start `terrad` installed from this repo on the same directory as `classic-terra/core` worked on. Then I receive error:

```
panic: runtime error: index out of range [7] with length 1
goroutine 155 [running]:
encoding/binary.bigEndian.Uint64(...)
        encoding/binary/binary.go:179
github.com/cosmos/cosmos-sdk/types.BigEndianToUint64(...)
        github.com/cosmos/cosmos-sdk@v0.44.8/types/utils.go:66
github.com/cosmos/cosmos-sdk/x/upgrade/keeper.Keeper.GetLastCompletedUpgrade({{0x7fff771d1edc, 0xe}, 0xc002618900, {0x27f55a8, 0xc002665f00}, {0x28194d0, 0xc00033d590}, 0xc002bb8330, {0x27f1e80, 0xc000236c40}, ...}, ...)
        github.com/cosmos/cosmos-sdk@v0.44.8/x/upgrade/keeper/keeper.go:250 +0x376
github.com/cosmos/cosmos-sdk/x/upgrade.BeginBlocker({{0x7fff771d1edc, 0xe}, 0xc002618900, {0x27f55a8, 0xc002665f00}, {0x28194d0, 0xc00033d590}, 0xc002bb8330, {0x27f1e80, 0xc000236c40}, ...}, ...)
        github.com/cosmos/cosmos-sdk@v0.44.8/x/upgrade/abci.go:30 +0x278
github.com/cosmos/cosmos-sdk/x/upgrade.AppModule.BeginBlock(...)
        github.com/cosmos/cosmos-sdk@v0.44.8/x/upgrade/module.go:130
github.com/cosmos/cosmos-sdk/types/module.(*Manager).BeginBlock(_, {{0x280a6d8, 0x375eba0}, {0x2818428, 0xc062b8f940}, {{0xb, 0x0}, {0xc0041b8382, 0xa}, 0xf81890, ...}, ...}, ...)
        github.com/cosmos/cosmos-sdk@v0.44.8/types/module/module.go:491 +0x19d
github.com/classic-terra/core/app.(*TerraApp).BeginBlocker(_, {{0x280a6d8, 0x375eba0}, {0x2818428, 0xc062b8f940}, {{0xb, 0x0}, {0xc0041b8382, 0xa}, 0xf81890, ...}, ...}, ...)
        github.com/classic-terra/core/app/app.go:273 +0xb3b
github.com/cosmos/cosmos-sdk/baseapp.(*BaseApp).BeginBlock(_, {{0xc062a78700, 0x20, 0x20}, {{0xb, 0x0}, {0xc0041b8382, 0xa}, 0xf81890, {0x3a9c7c14, ...}, ...}, ...})
        github.com/cosmos/cosmos-sdk@v0.44.8/baseapp/abci.go:177 +0x9db
github.com/tendermint/tendermint/abci/client.(*localClient).BeginBlockSync(_, {{0xc062a78700, 0x20, 0x20}, {{0xb, 0x0}, {0xc0041b8382, 0xa}, 0xf81890, {0x3a9c7c14, ...}, ...}, ...})
        github.com/tendermint/tendermint@v0.34.24/abci/client/local_client.go:280 +0xfe
github.com/tendermint/tendermint/proxy.(*appConnConsensus).BeginBlockSync(_, {{0xc062a78700, 0x20, 0x20}, {{0xb, 0x0}, {0xc0041b8382, 0xa}, 0xf81890, {0x3a9c7c14, ...}, ...}, ...})
        github.com/tendermint/tendermint@v0.34.24/proxy/app_conn.go:81 +0x55
github.com/tendermint/tendermint/state.execBlockOnProxyApp({0x280a710?, 0xc002bbdb60}, {0x28127d0, 0xc0015cf960}, 0xc062588960, {0x2819908, 0xc003b50000}, 0xf8188f?)
        github.com/tendermint/tendermint@v0.34.24/state/execution.go:307 +0x51d
github.com/tendermint/tendermint/state.(*BlockExecutor).ApplyBlock(_, {{{0xb, 0x0}, {0xc0061c97d0, 0x7}}, {0xc0061c97e0, 0xa}, 0x1, 0xf8188f, {{0xc007ba6b40, ...}, ...}, ...}, ...)
        github.com/tendermint/tendermint@v0.34.24/state/execution.go:140 +0x16b
github.com/tendermint/tendermint/blockchain/v0.(*BlockchainReactor).poolRoutine(0xc0061fe1c0, 0x0)
        github.com/tendermint/tendermint@v0.34.24/blockchain/v0/reactor.go:400 +0xb5a
created by github.com/tendermint/tendermint/blockchain/v0.(*BlockchainReactor).OnStart in goroutine 1
        github.com/tendermint/tendermint@v0.34.24/blockchain/v0/reactor.go:112 +0x6e
terrad.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
terrad.service: Failed with result 'exit-code'.
terrad.service: Consumed 1min 16.466s CPU time.
```

related issue: https://github.com/classic-terra/core/issues/403

**Comment by nghuyenthevinh2000** [comment]
https://github.com/classic-terra/core is currently the official repo of Terra Classic chain
